### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by pixelherodev** [floooh/fips-glfw#6]
After (finally) upgrading my laptop to an SSD, I decided to try out Wayland.

What I quickly noticed: while upstream GLFW has an option for Wayland support, fips-glfw does not.

Any way to add that back in? I experimented with it a bit but was unable to get it working properly. I'm not 100% sure as to what changes are made by fips, so it was rather difficult to try to fix.

**Comment by pixelherodev** [comment]
(Note: I needed this for an Oryol-based project).

Also, yes, I know that I should be able to get it working through GLX, but while many X11-based applications are working properly under XWayland, GLX itself appears to be missing completely. (I suspect the working ones are falling back to OSMesa or some such).

**Comment by floooh** [comment]
fips-glfw uses the original GLFW as git submodule (and this should also be quite uptodate), but it uses its own CMakeLists.txt file and glfw_config.h. I guess Wayland support isn't in because when fips-glfw was created it might not have existed yet in GLFW or was unstable.

To enable Wayland support it should be enough to add the missing source files in the fips-glfw CMakeLists.txt file, and (I think) add the _GLFW_WAYLAND define in the glfw_config.h file (both in the respective FIPS_LINUX sections). The question is whether this can be enabled together with _GLFW_GLX, or whether the two are mutually exclusive.

I have now idea how Wayland works, how to test it and whether my Linux laptop supports it though (it's a recent vanilla Ubuntu install), so it might be a bit of trial and error to get it working.

**Comment by pixelherodev** [comment]
If you don't know if you have it, chances are you don't.

I'll try to get this working again, I'll submit a patch if I do

**Comment by pixelherodev** [comment]
...okay, I got Oryol building over GLFW built for Wayland.

GLFW works fine. Oryol's GL renderer, however, most assuredly does _not_.

I'll fix up the patch for fips-GLFW and submit it soon, but the real issue is clearly Wayland support in Oryol.

**Comment by pixelherodev** [comment]
I take that back - the mistake was on my end.

I made the mistake of partly switching Oryol's renderer over to GLESv2 because Wayland uses EGL so I assumed that was needed.

NOPE!

So, made a few other tweaks here and there, got Oryol working under Wayland.

Going to s

**Comment by pixelherodev** [comment]
Closing this issue, should have a PR open tonight or tomorrow on fips-libs/fips-glfw
